flntr_project/flntr_app/urls.py
from django.conf.urls import url
from flntr_app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/', views.about, name='about'),
    url(r'^search/$', views.search, name='search'),
	url(r'^results/$', views.results, name='results'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^property/$', views.property, name='property'),
    url(r'^property/(?P<flat_id_slug>[\w\-]+)/$',
        views.show_property, name='show_property'),
    url(r'^property/(?P<flat_id_slug>[\w\-]+)/(?P<student_profile_slug>[\w\-]+)/profile$',
        views.show_property_user_profile, name='show_property_user_profile'),
    # url(r'^user/(?P<user_id_slug>[\w\-]+)/$',
    #     views.show_user, name='show_user'),
    url(r'^user/(?P<landlord_id_slug>[\w\-]+)/requests/$',
        views.show_user_requests, name='show_user_requests'),
    url(r'^user/(?P<landlord_id_slug>[\w\-]+)/requests/(?P<student_profile_slug>[\w\-]+)/$',
        views.show_user_requests_aRequest, name='show_user_requests_aRequest'),
    url(r'^user/(?P<landlord_id_slug>[\w\-]+)/requests/(?P<student_profile_slug>[\w\-]+)/$',
        views.show_user_requests_profile, name='show_user_requests_profile'),
    url(r'^user/my-account/$',
        views.show_user_account, name='show_user_account'),
    url(r'^user/(?P<student_profile_slug>[\w\-]+)/profile/$',
        views.show_user_profile, name='show_user_profile'),
    url(r'^edit-profile/$',
        views.edit_profile, name='edit_profile'),
    url(r'^delete-profile/$',
        views.delete_profile, name='delete_profile'),
    url(r'^user/(?P<user_id_slug>[\w\-]+)/invitations/$',
        views.show_user_invitations, name='show_user_invitations'),
    url(r'^user/(?P<landlord_id_slug>[\w\-]+)/property/$',
        views.show_user_properties, name='show_user_properties'),
    url(r'^user/(?P<landlord_id_slug>[\w\-]+)/property/(?P<flat_id_slug>[\w\-]+)/$',
        views.show_user_properties_aProperty, name='show_user_properties_aProperty'),
    url(r'^logout/$', views.user_logout, name='logout'),
	url(r'^add_flat/$', views.add_flat, name='add_flat'),
	url(r'^property/(?P<flat_id_slug>[\w\-]+)/send_request/(?P<room_number>[\w\-]+)$',
        views.send_request, name='send_request'),
    url(r'^edit_flat/(?P<flat_id_slug>[\w\-]+)/$', views.edit_flat, name='edit_flat'),
    url(r'^delete_flat/(?P<flat_id_slug>[\w\-]+)/$', views.delete_flat, name='delete_flat'),
    url(r'^change_password/$', views.change_password, name='change_password'),
]

flntr_project/flntr_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from flntr_app import views
from registration.backends.simple.views import RegistrationView

class MyRegistrationView(RegistrationView):
    def get_success_url(self, request, user):
        return '/flntr/'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^flntr/', include('flntr_app.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# registration.backends.simple.urls:
# • registration->/accounts/register/
# • registrationcomplete->/accounts/register/complete/ • login->/accounts/login/
# • logout->/accounts/logout/
# • passwordchange->/password/change/
# • passwordreset->/password/reset/

flntr_project/flntr_app/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.template.defaultfilters import slugify
from datetime import datetime
from decimal import Decimal

class Landlord(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE,)
	slug = models.SlugField(unique=True)

	def save(self, *args, **kwargs):
		self.slug = slugify(self.user.first_name + " " + self.user.last_name)
		super(Landlord, self).save(*args, **kwargs)

	def __str__(self):
		return self.user.username

class Flat(models.Model):
	owner = models.ForeignKey(Landlord)
	title = models.CharField(max_length=250)
	numberOfRooms = models.IntegerField(default=0)
	availableRooms = models.IntegerField(default=0)
	streetAddress = models.CharField(max_length=64)
	postCode = models.CharField(max_length=8)
	description = models.TextField(blank=True,)
	averageRoomPrice = models.DecimalField(max_digits=6, decimal_places=2, null=True)
	slug = models.SlugField(unique=True)
	dayAdded = models.DateTimeField(default=datetime.now)
	views = models.IntegerField(default=0)
	distanceFromUniversity = models.IntegerField(default = 0)
	distanceText = models.CharField(max_length=8, default = "0 mi")
	latitude = models.DecimalField(max_digits=12, decimal_places=8, default = 0)
	longitude = models.DecimalField(max_digits=12, decimal_places=8, default = 0)
	averageAge = models.DecimalField(max_digits=4, decimal_places=1, null=True)
	flatmateGender = models.CharField(max_length=6, null=True)

	def save(self, *args, **kwargs):
		self.slug = slugify(self.streetAddress)
		self.averageAge = calculateAverageAge(self)
		self.flatmateGender = calculateGenderProfile(self)
		super(Flat, self).save(*args, **kwargs)
	def __str__(self):
		return self.title

def calculateAverageAge(flat):
	try:
		rooms = Room.objects.filter(flat=flat)
		num_students = 0
		total_age = 0
		for room in rooms:
			if not room is None:
				user = room.student
				if not user is None:
					num_students += 1
					total_age += user.age
		if(num_students > 0):
			return round((total_age/num_students),2)
		else:
			return None
	except Room.DoesNotExist:
		return None

def calculateGenderProfile(flat):
	try:
		rooms = Room.objects.filter(flat=flat)
		flat_gender = flat.flatmateGender
		student_count = 0
		for room in rooms:
			if not room is None:
				user = room.student
				if not user is None:
					student_count += 1
					if student_count == 1:
						flat_gender = user.gender
					else:
						if user.gender != flat_gender:
							return 'mixed'
				#return flat_gender
	except Room.DoesNotExist:
		return None
	return flat_gender

class StudentProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE,)
	picture = models.ImageField(upload_to='profile_images', blank=True)
	bio = models.TextField(blank=True)
	properties = models.ForeignKey(Flat, null=True, blank=True)
	age = models.IntegerField(default=0)
	gender = models.CharField(max_length=10)
	slug = models.SlugField(unique=True)

	def save(self, *args, **kwargs):
		self.slug = slugify(self.user.first_name + " " + self.user.last_name)
		super(StudentProfile, self).save(*args, **kwargs)

	def __str__(self):
		return self.user.username

class Room(models.Model):
	flat = models.ForeignKey(Flat)
	roomNumber = models.IntegerField()
	size = models.CharField(max_length=8)
	price = models.DecimalField(max_digits=9, decimal_places=2)
	student = models.OneToOneField(StudentProfile, null=True, blank=True)

	def __str__(self):
		if (self.price < 0):
			self.price = 0
		return "%s %s" % (self.flat.title, self.roomNumber)

class FlatImage(models.Model):
	flat = models.ForeignKey(Flat, related_name='images')
	imageNumber = models.IntegerField(default=0)
	image = models.ImageField(upload_to='flat_images', blank=True)

	def __str__(self):
		return "%s %s" % (self.flat.title, self.imageNumber)

class Request(models.Model):
	room = models.ForeignKey(Room)
	landlord = models.ForeignKey(Landlord, null=True, blank=True)
	student = models.OneToOneField(StudentProfile)
	message = models.TextField(blank=True)

	#def save(self):
	#	if not self.id:
	#		self.landlord = self.room.flat.owner
	#	super(Request, self).save()

	def __str__(self):
		return "%s %s" % (self.room, self.student)

#class SocialAccount(models.Model):
#	user = models.OneToOneField(User, on_delete=models.CASCADE,)
#	type = models.CharField(max_length=2)

flntr_project/templates/flntr/add_flat_error.html
{% extends 'flntr/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Send Request
{% endblock %}

{% block body_block %}

        <h3>Could not find {{ address }}</h3>
        Check your inputs and <a href="{% url 'add_flat' %}">try again</a>

{% endblock %}

flntr_project/templates/flntr/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
	<head>
		<meta charset="utf-8">
    	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  		<meta name="viewport" content="width=device-width, initial-scale=1">
  		<title>
  			{% block title_block %}
  			{% endblock %}
  		</title>

  		<!-- Bootstrap core CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    	<!-- Custom styles for this template -->
    	<link rel="stylesheet" type="text/css" href="{% static 'CSS/flntr.css' %}">

		<!-- Custom styles for maps -->
    	<link rel="stylesheet" type="text/css" href="{% static 'CSS/maps.css' %}">

		<!-- Custom styles for flat views -->
		<link rel="stylesheet" type="text/css" href="{% static 'CSS/flats.css' %}">

	</head>
	<body>
   		<nav class="navbar navbar-expand navbar-custom navbar-fixed-top">
      		<div class="container">
        		<div class="navbar-header">
 	 				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    				<span class="navbar-toggler-icon"></span>
  					</button>
          			<a class="navbar-brand" href="{% url 'index' %}">flntr</a>
        		</div>
         		<div id="navbar" class="collapse navbar-collapse">
          			<ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">About</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'search' %}">Search</a></li>
          			{% if user.is_authenticated %}
        				{% if perms.flntr_app.add_flat %}
        				<li class="nav-item"><a class="nav-link" href="{% url 'add_flat' %}">Add Flat</a></li>
        				<li class="nav-item"><a class="nav-link" href="{% url 'show_user_account' %}">Manage Flats &amp; Account</a></li>
        				{% endif %}
        				{% if perms.flntr_app.change_studentprofile %}
        				<li class="nav-item"><a class="nav-link" href="{% url 'show_user_account' %}">View My Profile</a></li>
                {% endif %}
                <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                </ul>
                <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Log In</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Register</a></li>
      {% endif %}
      </ul>
        </div><!-- /.nav-collapse -->
      </div>
    </nav>
  <div class="container">
		<div class="background">
			{% block body_block %}
			{% endblock %}
		</div>

  </div>
	<hr>
	<div class="container">
		<ul>
			{% if user.is_authenticated %}
			<li><a href="{% url 'logout' %}">Logout</a></li>
				{% if perms.flntr_app.add_flat %}
				<li><a href="{% url 'add_flat' %}">Add Flat</a></li>
        <li><a href="{% url 'show_user_account' %}">Manage Flats</a></li>
				{% endif %}
				{% if perms.flntr_app.change_studentprofile %}
				<li><a href="{% url 'show_user_account' %}">View My Profile</a></li>
				{% endif %}
			{% else %}
			<li><a href="{% url 'login' %}">Log In</a></li>
			<li><a href="{% url 'register' %}">Register</a></li>
			{% endif %}
			<li><a href="{% url 'about' %}">About</a></li>
			<li><a href="{% url 'index' %}">Homepage</a></li>
			<li><a href="{% url 'search' %}">Search</a></li>
   		</ul>
  </div>
  <hr />

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  </body>


</html>

flntr_project/templates/flntr/change_password.html
{% extends 'flntr/base.html' %}
{% load staticfiles %}

{% block title_block %}
	flntr - Change password
{% endblock %}

{% block body_block %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<form method="post">
  {% csrf_token %}
	{% load bootstrap %}
  {{ change_password_form|bootstrap_horizontal }}
  <button class="btn btn-primary" type="submit">Save changes</button>
</form>
{% endblock %}

flntr_project/templates/flntr/delete_profile.html
{% extends 'flntr/base.html' %}
{% load staticfiles %}

{% block title_block %}
	flntr - Delete Profile
{% endblock %}

{% block body_block %}
	<div>
		<br>
		<br>
		<h2>{{ studentprofile.user.first_name }} {{ studentprofile.user.last_name }}'s Profile</h2>
	</div>
  {% if deleted %}

  {% else %}
	<ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>

    <form id="delete_form" action="/flntr/delete-profile/" method="post">
    	{% csrf_token %}
    	To delete your profile type in your password below. This can not be reversed.
      <br>
      <br>
    	Password: <input class="btn btn-primary" type="password" name="password" value=""	size="50" />
    	<br>
      <br>
    	<input type="submit" name="submit" value="Delete Profile" />
    </form>
	<br><br>
{% endif %}
{% endblock %}

flntr_project/templates/flntr/edit_flat.html
{% extends 'flntr/base.html' %}
{% load staticfiles %}

{% block title_block %}
	flntr - Edit Flat
{% endblock %}

{% block body_block %}
	<div>
		<br>
		<br>
		<h2>{{ flat.title }}</h2>
	</div>
  <form Id="edit_flat_form" action="{% url 'edit_flat' flat.slug %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{% load bootstrap %}
		{{ edit_flat_form|bootstrap_horizontal }}

		<input class="btn btn-primary"  type="submit" name="submit" value="Update Flat" />

	</form>
	<br><br>
  <a href="{% url 'delete_flat' flat.slug %}"><button type="button"
		class="btn btn-default"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Delete Flat</button></a>

{% endblock %}

flntr_project/templates/flntr/edit_profile.html
{% extends 'flntr/base.html' %}
{% load staticfiles %}

{% block title_block %}
flntr - Edit Profile
{% endblock %}

{% block body_block %}
	<div>
		<br>
		<br>
		<h2>{{ studentprofile.user.first_name }} {{ studentprofile.user.last_name }}'s Profile</h2>
	</div>
  <form Id="profile_form" action="{% url 'edit_profile' %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{% load bootstrap %}

		{{ profile_form|bootstrap_horizontal }}
			{{ age_form|bootstrap_horizontal }}


		<input class="btn btn-primary" type="submit" name="submit" value="Update Profile" />

	</form>
	<br><br>
	<a href="{% url 'delete_profile' %}"><button type="button"
		class="btn btn-danger"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Delete Account</button></a>
		<a href="{% url 'change_password' %}"><button type="button"
			class="btn btn-info"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Change Password</button></a>

{% endblock %}

flntr_project/templates/flntr/index.html
{% extends 'flntr/base.html' %}
{% load staticfiles %}

{% block title_block %}
	flntr - Home
{% endblock %}

{% block body_block %}

<style>
.flat-view {
	box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
   	transition: 0.3s;
    margin: 20px 20px 0 0;
    border-radius: 5px;
    overflow: auto
}

.flat-view:hover {
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.4);
}

.flat-image {
    float: left;
}
.flat-image img {
    display: block
}
.flat-description {
    margin-left: 210px
}
.post-title {
    font-weight: bold;
    padding: 10px;
    background: #ccc
}

.jumbotronn{
    position: relative;
    padding:0 !important;
    margin-top:70px !important;
    background: #ffffff;
    margin-top: 23px;
    text-align:center;
    margin-bottom: 70px !important;
}






</style>
<div class="container-fluid">


<div class="container-fluid">
	<div class="jumbotronn">
		<h1 class="display-3">Welcome to flntr</h1>
		<p class="lead">For easier flatsharing</p>
	</div>

</div>
<hr>
	<div class="jumbotron-fluid">
		<h2 class="text-align">Most Recent Flats</h2>
		{% if recentflats %}
			<ul>
			{% for flat in recentflats %}

			<div class="flat-view" style="cursor: pointer;" onclick="window.location='{% url 'show_property' flat.slug %}';">
    			<h4 class="post-title">{{flat.title}}</h4>
    			<div class="flat-image">
					<img width="200" height="200" src="{% for flatimage in recent_flat_images %} {% if flatimage.flat == flat %} {{ MEDIA_URL }}{{ flatimage.image.url }} {% endif %} {% endfor %}" alt="No image available" onerror="this.onerror=null;this.src='{% static 'img/alt_flat_image.png' %}';"/>
				</div>
    			<div class="flat-description">
        			<p>{{flat.description}}</p>
					<ul>
						<li>Location: {{ flat.streetAddress }}</li>
						<li>Average Price per Room: £{{ flat.averageRoomPrice }}</li>
						<li>Date added: {{ flat.dayAdded }}</li>
					</ul>
				</div>
			</div>

				<!-- <li><a href="{% url 'show_property' flat.slug %}">{{ flat.title }}</a></li>
				<ul>
					<li>Location: {{ flat.streetAddress }}</li>
					<li>Average Price per Room: {{ flat.averageRoomPrice }}</li>
					<li>Date added: {{ flat.dayAdded }}</li>
				</ul> -->
			{% endfor %}
			</ul>
		{% else %}
			There are no rooms
		{% endif %}
	</div>
<hr>
	<div class="jumbotron-fluid">
		<h2 class="text-align">Most Viewed Flats</h2>
		{% if mostviewed %}
			<ul>
			{% for flat in mostviewed %}
			<div class="flat-view" style="cursor: pointer;" onclick="window.location='{% url 'show_property' flat.slug %}';">
    			<h4 class="post-title">{{flat.title}}</h4>
    			<div class="flat-image">
					<img width="200" height="200" src="{% for flatimage in viewed_flat_images %} {% if flatimage.flat == flat %} {{ MEDIA_URL }}{{ flatimage.image.url }} {% endif %} {% endfor %}" alt="idk"/>
				</div>
    			<div class="flat-description">
        			<p>{{flat.description}}</p>
					<ul>
						<li>Location: {{ flat.streetAddress }}</li>
						<li>Average Price per Room: £{{ flat.averageRoomPrice }}</li>
						<li>Date added: {{ flat.dayAdded }}</li>
					</ul>
				</div>
			</div>
			{% endfor %}
			</ul>
		{% else %}
			There are no rooms available.
		{% endif %}
	</div>

	<div class="container">
		<ul>
			<li><a href="{% url 'property' %}"><button type="button" class="btn btn-info">View all flats</button></a></li>
		</ul>
	</div>
</div>
{% endblock %}

flntr_project/templates/flntr/login.html
{% extends 'flntr/base.html' %}
{% load staticfiles %}

{% block title_block %}
	flntr - Login
{% endblock %}

{% block body_block %}
<br>
<div align="center">
	<h1>Login to flntr</h1>
</div>
<br>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<div class="container-fluid">
	<div align="center">


	<form id="login_form" action="/flntr/login/" method="post">
		{% csrf_token %}
		{% load bootstrap %}
		{{ login_form|bootstrap_horizontal:'col-lg-8'}}


		<input class="btn btn-primary" type="submit" value="Login" />

	</form>
		</div>
</div>
<br><br>

{% endblock %}

flntr_project/templates/flntr/register.html
    {% extends 'flntr/base.html' %}
{% load staticfiles %}

{% block title_block %}
    flntr - Register
{% endblock %}

{% block body_block %}

<div class="container-fluid">
  <div align="center">

<br><br>
<h1>Register with flntr</h1>
{% if registered %}
	<strong>thank you for registering!</strong>
	<a href="{% url 'index' %}">Return to the homepage.</a><br />
{% else %}



    <form class="fb_login_form" action="index.html" method="post">




        <div class="fb-login-button" scope="public_profile,email" data-width="250" data-max-rows="1" data-size="large" data-button-type="login_with" data-show-faces="false" data-auto-logout-link="false" data-use-continue-as="true"></div>
    </form>

<hr>
	<form Id="user_form" action="{% url 'register' %}" method="post" enctype="multipart/form-data">
	{% csrf_token %}
  {% load bootstrap %}

  {{ user_form|bootstrap_horizontal }}
    {{ age_form|bootstrap_horizontal }}
    <strong>I am a:</strong>
    <select name="group_choice">
      <option value="Student">Student</option>
      <option value="Landlord">Landlord</option>
    </select>
    <br> <br>
		<input class="btn btn-primary" type="submit" name="submit" id="submit_button" value="Register" />

	</form>
{% endif %}

</div>
</div>
{% endblock %}

flntr_project/templates/flntr/request_sent.html
{% extends 'flntr/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Send Request
{% endblock %}

{% block body_block %}

    {% if has_requested %}
        <h3>You have already sent a request</h3>
    {% else %}
        {% if has_flat %}
            <h3>This Student has already been assigned a flat</h3>
        {% else %}
            <h3>Your request has been sent</h3>
        {% endif %}

    {% endif %}
    <a href="{% url 'index' %}"><button type="button" class="btn btn-info">Return to Homepage</button></a>


{% endblock %}

flntr_project/templates/flntr/results.html
{% extends 'flntr/base.html' %}
{% load staticfiles %}

{% block title_block %}
	flntr - Results
{% endblock %}

{% block body_block %}

	<h1>Results</h1>

	{% if results %}
	<a href="#big-map"><button type="button" class="btn btn-info">View All Properties on Map</button></a>
		<ul>
		{% for flat in results %}
		<div class="flat-view" style="cursor: pointer;" onclick="window.location='{% url 'show_property' flat.slug %}';">
			<h4 class="post-title">{{flat.title}}</h4>
			<div class="flat-image">
				<img width="200" height="200" src="{% for flatimage in flat_images %} {% if flatimage.flat == flat %} {{ MEDIA_URL }}{{ flatimage.image.url }} {% endif %} {% endfor %}" alt="No image available"  onerror="this.onerror=null;this.src='{% static 'img/alt_flat_image.png' %}';"%}/>
			</div>
			<div class="flat-description">
				<p>{{flat.description}}</p>
				<ul>
					<li>Location: {{ flat.streetAddress }}</li>
					<li>Average Price per Room: £{{ flat.averageRoomPrice }}</li>
					<li>Date added: {{ flat.dayAdded }}</li>
				</ul>
			</div>
		</div>

		{% endfor %}
		</ul>
		<br/><br/>
		<div id="big-map"></div>
			<script>
			  var map;
			  function initMap() {
				map = new google.maps.Map(document.getElementById('big-map'), {
				  center: {lat: 55.8721211, lng:-4.2882},
				  zoom: 14
				});

				var LatLng;
				var infowindows = [];

					{% for flat in results %}
					LatLng = {lat: parseFloat("{{flat.latitude}}"), lng: parseFloat("{{flat.longitude}}")};
						var marker{{flat.pk}} = new google.maps.Marker({
						position: LatLng,
						map: map,
						title: "{{flat.title}}",
						animation: google.maps.Animation.DROP
						});

						var contentString{{flat.pk}} = "<h6><a href=\"{% url 'show_property' flat.slug %}\">{{ flat.title }}</a></h6></br>"
						+ "<div>" + "{{flat.description}}" + "<ul>" + "<li>£{{flat.averageRoomPrice}}</li><li>{{flat.numberOfRooms}}</li><li>£{{flat.streetAddress}}</li><li>£{{flat.distanceText}} from University</li></ul></div>";

						var infowindow{{flat.pk}} = new google.maps.InfoWindow({
						content: contentString{{flat.pk}}
						});
						infowindows.push(infowindow{{flat.pk}});

						marker{{flat.pk}}.addListener('click', function() {
							for(var i = 0; i < infowindows.length; i++){
								infowindows[i].close();
							}
							infowindow{{flat.pk}}.open(map, marker{{flat.pk}});
						});


					{% endfor %}



			  }
			</script>
			<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBW0crhPrG5Yc6_hh9fbjb8_LqqW2Je3Ho&callback=initMap"
			async defer></script>








	{% else %}
		No Rooms matching your criteria
		</br><a href="{% url 'search' %}">Back to Search</a>
	{% endif %}



{% endblock %}

flntr_project/templates/flntr/send_request.html
{% extends 'flntr/base.html' %}

{% block title_block %}
	flntr - Request
{% endblock %}
{% block body_block %}
	<form  method="post" action="{% url 'send_request' flat.slug room.roomNumber %}">
		{% csrf_token %}
				{% load bootstrap %}
		{{ request_form|bootstrap_horizontal }}
		<input class="btn btn-primary" type="submit" name="submit" value="Send"/>
	</form>
{% endblock %}